
import java.sql.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import oracle.jdbc.pool.OracleDataSource;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hitea
 */
public class DesignPage extends javax.swing.JFrame {

    /**
     * Creates new form DesignPage
     */
    public DesignPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        enrollmentPanel = new javax.swing.JPanel();
        enrollmentButtonPanel = new javax.swing.JLabel();
        deletePanel = new javax.swing.JPanel();
        deleteButtonPanel = new javax.swing.JLabel();
        dropPanel = new javax.swing.JPanel();
        dropButtonPanel = new javax.swing.JLabel();
        displayPanel = new javax.swing.JPanel();
        displayButtonPanel = new javax.swing.JLabel();
        displayTableComboBox = new javax.swing.JComboBox<>();
        searchPanel = new javax.swing.JPanel();
        searchButtonPanel = new javax.swing.JLabel();
        upperPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setName("mainFrame"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(620, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(54, 33, 89));
        sidePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        sidePanel.setName("sidePanel"); // NOI18N

        enrollmentPanel.setBackground(new java.awt.Color(54, 33, 113));
        enrollmentPanel.setName("displayPanel"); // NOI18N
        enrollmentPanel.setPreferredSize(new java.awt.Dimension(250, 90));
        enrollmentPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enrollmentPanelMousePressed(evt);
            }
        });
        enrollmentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enrollmentButtonPanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        enrollmentButtonPanel.setForeground(new java.awt.Color(255, 255, 255));
        enrollmentButtonPanel.setText("Enrollment");
        enrollmentButtonPanel.setName("displayButtonPanel"); // NOI18N
        enrollmentButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enrollmentButtonPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                enrollmentButtonPanelMouseReleased(evt);
            }
        });
        enrollmentPanel.add(enrollmentButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 100, 60));

        deletePanel.setBackground(new java.awt.Color(54, 33, 113));
        deletePanel.setName("displayPanel"); // NOI18N
        deletePanel.setPreferredSize(new java.awt.Dimension(250, 90));
        deletePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deletePanelMousePressed(evt);
            }
        });
        deletePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteButtonPanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deleteButtonPanel.setForeground(new java.awt.Color(255, 255, 255));
        deleteButtonPanel.setText("Delete");
        deleteButtonPanel.setName("displayButtonPanel"); // NOI18N
        deleteButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteButtonPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deleteButtonPanelMouseReleased(evt);
            }
        });
        deletePanel.add(deleteButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 80, 66));

        dropPanel.setBackground(new java.awt.Color(54, 33, 113));
        dropPanel.setName("displayPanel"); // NOI18N
        dropPanel.setPreferredSize(new java.awt.Dimension(250, 90));
        dropPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dropPanelMousePressed(evt);
            }
        });
        dropPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dropButtonPanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dropButtonPanel.setForeground(new java.awt.Color(255, 255, 255));
        dropButtonPanel.setText("Drop");
        dropButtonPanel.setName("displayButtonPanel"); // NOI18N
        dropButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dropButtonPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dropButtonPanelMouseReleased(evt);
            }
        });
        dropPanel.add(dropButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 60, 60));

        displayPanel.setBackground(new java.awt.Color(85, 85, 116));
        displayPanel.setMinimumSize(new java.awt.Dimension(250, 90));
        displayPanel.setName("displayPanel"); // NOI18N
        displayPanel.setPreferredSize(new java.awt.Dimension(250, 90));
        displayPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                displayPanelMousePressed(evt);
            }
        });
        displayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayButtonPanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        displayButtonPanel.setForeground(new java.awt.Color(255, 255, 255));
        displayButtonPanel.setText("  Display Table");
        displayButtonPanel.setName("displayButtonPanel"); // NOI18N
        displayPanel.add(displayButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 140, 30));

        displayTableComboBox.setBackground(new java.awt.Color(240, 240, 240));
        displayTableComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "TA", "Classes", "Courses", "Enrollments", "Prereq", "Logs" }));
        displayTableComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayTableComboBoxActionPerformed(evt);
            }
        });
        displayPanel.add(displayTableComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 140, 30));

        searchPanel.setBackground(new java.awt.Color(54, 33, 113));
        searchPanel.setMinimumSize(new java.awt.Dimension(250, 90));
        searchPanel.setName("displayPanel"); // NOI18N
        searchPanel.setPreferredSize(new java.awt.Dimension(250, 90));
        searchPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchPanelMousePressed(evt);
            }
        });
        searchPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchButtonPanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchButtonPanel.setForeground(new java.awt.Color(255, 255, 255));
        searchButtonPanel.setText("Search");
        searchButtonPanel.setName("displayButtonPanel"); // NOI18N
        searchButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchButtonPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                searchButtonPanelMouseReleased(evt);
            }
        });
        searchPanel.add(searchButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 70, 66));

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
            .addComponent(dropPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(deletePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(enrollmentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(searchPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(enrollmentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(dropPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(deletePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 1030));

        upperPanel.setBackground(new java.awt.Color(122, 72, 222));
        upperPanel.setName("upperPanel"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Registration System");

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperPanelLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(upperPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 830, 100));

        displayTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2));
        displayTable.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(displayTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 125, 830, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayPanelMousePressed
        // TODO add your handling code here:
        System.out.println("Button Display Clicked");
    }//GEN-LAST:event_displayPanelMousePressed

    private void enrollmentPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrollmentPanelMousePressed
        // TODO add your handling code here:
        System.out.println("Button Clicked Enrollment");
        dispose();
        EnrollmentPage ep = new EnrollmentPage();
        ep.setVisible(true);
    }//GEN-LAST:event_enrollmentPanelMousePressed

    private void enrollmentButtonPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrollmentButtonPanelMousePressed
        // TODO add your handling code here:
        // Do Not Use this Method
    }//GEN-LAST:event_enrollmentButtonPanelMousePressed

    private void enrollmentButtonPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrollmentButtonPanelMouseReleased
        // TODO add your handling code here:
        // Do Not Use this Method
    }//GEN-LAST:event_enrollmentButtonPanelMouseReleased

    private void dropButtonPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropButtonPanelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropButtonPanelMousePressed

    private void dropButtonPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropButtonPanelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dropButtonPanelMouseReleased

    private void dropPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropPanelMousePressed
        // TODO add your handling code here:
        dispose();
        DropPage dp = new DropPage();
        dp.setVisible(true);
    }//GEN-LAST:event_dropPanelMousePressed

    private void deleteButtonPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonPanelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonPanelMousePressed

    private void deleteButtonPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonPanelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonPanelMouseReleased

    private void deletePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletePanelMousePressed
        // TODO add your handling code here:
         dispose();
        DeletePage dp = new DeletePage();
        dp.setVisible(true);
    }//GEN-LAST:event_deletePanelMousePressed

    private void searchButtonPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonPanelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonPanelMousePressed

    private void searchButtonPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonPanelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonPanelMouseReleased

    private void searchPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchPanelMousePressed
        // TODO add your handling code here:
        dispose();
        SearchPage dp = new SearchPage();
        dp.setVisible(true);
    }//GEN-LAST:event_searchPanelMousePressed

    private void displayTableComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayTableComboBoxActionPerformed

         /*
        INPUT this will be any option selected from combo box
        OUTPUT will be displayed in table as all entries from selected table
        */
        if (evt.getSource() == displayTableComboBox) {

            JComboBox cb = (JComboBox) evt.getSource();
            String msg = (String) cb.getSelectedItem();
             OracleDataSource ds;
             Connection conn = null;
            try {
                ds = new oracle.jdbc.pool.OracleDataSource();
                ds.setURL("jdbc:oracle:thin:@castor.cc.binghamton.edu:1521:acad111");
                conn = ds.getConnection("hmense1", "HIMItejas06");
                System.out.println("Database Connection Successful");
         /*
            Options for Displaying tables
            Student
            TA
            Classes
            Courses
            Enrollments
            Prereq
            Logs
             */
            switch (msg) {

                case "Student":
                   
                    try {
                        Statement stmt = conn.createStatement();
                        // Save result
                        ResultSet rset;
                        rset = stmt.executeQuery("SELECT * FROM students");
                        displayTable.setModel(DbUtils.resultSetToTableModel(rset));
                    } catch (SQLException ex) {
                        System.out.println(ex);
                        System.out.println("Error in data retrieval");
                        JOptionPane.showMessageDialog(null,
                                "Oops, Some Error occured!",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                        //Logger.getLogger(DesignPage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    break;
                    
                case "TA":
                    try {
                       Statement stmt = conn.createStatement();
                       // Save result
                        ResultSet rset;
                        rset = stmt.executeQuery("SELECT * FROM TAs");
                        displayTable.setModel(DbUtils.resultSetToTableModel(rset));
                    } catch (SQLException ex) {
                        System.out.println(ex);
                        System.out.println("Error in data retrieval");
                        JOptionPane.showMessageDialog(null,
                                "Oops, Some Error occured!",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                    }
                     break;
                     
                     case "Classes":
                    try {
                        Statement stmt = conn.createStatement();
                        // Save result
                        ResultSet rset;
                        rset = stmt.executeQuery("SELECT * FROM classes");
                        displayTable.setModel(DbUtils.resultSetToTableModel(rset));
                    } catch (SQLException ex) {
                        System.out.println(ex);
                        System.out.println("Error in data retrieval");
                        JOptionPane.showMessageDialog(null,
                                "Oops, Some Error occured!",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                    }
                    break;
                    
                    case "Courses":
                    try {
                        Statement stmt = conn.createStatement();
                        // Save result
                        ResultSet rset;
                        rset = stmt.executeQuery("SELECT * FROM courses");
                        displayTable.setModel(DbUtils.resultSetToTableModel(rset));
                    } catch (SQLException ex) {
                        System.out.println(ex);
                        System.out.println("Error in data retrieval");
                        JOptionPane.showMessageDialog(null,
                                "Oops, Some Error occured!",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                        //Logger.getLogger(DesignPage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    break;
                    
                    case "Enrollments":
                    try {
                        Statement stmt = conn.createStatement();
                        // Save result
                        ResultSet rset;
                        rset = stmt.executeQuery("SELECT * FROM enrollments");
                        displayTable.setModel(DbUtils.resultSetToTableModel(rset));
                    } catch (SQLException ex) {
                        System.out.println(ex);
                        System.out.println("Error in data retrieval");
                        JOptionPane.showMessageDialog(null,
                                "Oops, Some Error occured!",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                        //Logger.getLogger(DesignPage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    break;
                    
                    case "Prereq":
                    try {
                        Statement stmt = conn.createStatement();
                        // Save result
                        ResultSet rset;
                        rset = stmt.executeQuery("SELECT * FROM prerequisites");
                        displayTable.setModel(DbUtils.resultSetToTableModel(rset));
                    } catch (SQLException ex) {
                        System.out.println(ex);
                        System.out.println("Error in data retrieval");
                        JOptionPane.showMessageDialog(null,
                                "Oops, Some Error occured!",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                        //Logger.getLogger(DesignPage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    break;
                    
                    case "Logs":
                    try {
                        Statement stmt = conn.createStatement();
                        // Save result
                        ResultSet rset;
                        rset = stmt.executeQuery("SELECT * FROM logs");
                        displayTable.setModel(DbUtils.resultSetToTableModel(rset));
                    } catch (SQLException ex) {
                        System.out.println(ex);
                        System.out.println("Error in data retrieval");
                        JOptionPane.showMessageDialog(null,
                                "Oops, Some Error occured!",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                        //Logger.getLogger(DesignPage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    break;
                default: 
                    System.out.println("Default case");
                     break;
            }
            // Databse Connection Catch Block
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,
                                "Oops, Some Error occured as could not esatblish a connection!",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
               // Logger.getLogger(DesignPage.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                try {
                    conn.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,
                                "Oops, Some Error occured as could not close a esatblished a connection properly!",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                    //Logger.getLogger(DesignPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_displayTableComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesignPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesignPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesignPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesignPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesignPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deleteButtonPanel;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JLabel displayButtonPanel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JTable displayTable;
    private javax.swing.JComboBox<String> displayTableComboBox;
    private javax.swing.JLabel dropButtonPanel;
    private javax.swing.JPanel dropPanel;
    private javax.swing.JLabel enrollmentButtonPanel;
    private javax.swing.JPanel enrollmentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel searchButtonPanel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables
}
