
import java.sql.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import oracle.jdbc.OracleTypes;
import oracle.jdbc.pool.OracleDataSource;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hitea
 */
public class DropPage extends javax.swing.JFrame {

    /**
     * Creates new form DesignPage
     */
    public DropPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        enrollmentPanel = new javax.swing.JPanel();
        enrollmentButtonPanel = new javax.swing.JLabel();
        deletePanel = new javax.swing.JPanel();
        deleteButtonPanel = new javax.swing.JLabel();
        dropPanel = new javax.swing.JPanel();
        dropButtonPanel = new javax.swing.JLabel();
        displayPanel = new javax.swing.JPanel();
        displayButtonPanel = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        searchButtonPanel = new javax.swing.JLabel();
        upperPanel = new javax.swing.JPanel();
        studentBIDLabel = new javax.swing.JLabel();
        studentBIdTextField = new javax.swing.JTextField();
        dropStudentButton = new javax.swing.JButton();
        classIdTextField = new javax.swing.JTextField();
        ClassIDLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setName("mainFrame"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(54, 33, 89));
        sidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        sidePanel.setName("sidePanel"); // NOI18N

        enrollmentPanel.setBackground(new java.awt.Color(85, 85, 116));
        enrollmentPanel.setName("displayPanel"); // NOI18N
        enrollmentPanel.setPreferredSize(new java.awt.Dimension(250, 90));
        enrollmentPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enrollmentPanelMousePressed(evt);
            }
        });
        enrollmentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enrollmentButtonPanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        enrollmentButtonPanel.setForeground(new java.awt.Color(255, 255, 255));
        enrollmentButtonPanel.setText("Enrollment");
        enrollmentButtonPanel.setName("displayButtonPanel"); // NOI18N
        enrollmentButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enrollmentButtonPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                enrollmentButtonPanelMouseReleased(evt);
            }
        });
        enrollmentPanel.add(enrollmentButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 125, 60));

        deletePanel.setBackground(new java.awt.Color(85, 85, 116));
        deletePanel.setName("displayPanel"); // NOI18N
        deletePanel.setPreferredSize(new java.awt.Dimension(250, 90));
        deletePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deletePanelMousePressed(evt);
            }
        });
        deletePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteButtonPanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deleteButtonPanel.setForeground(new java.awt.Color(255, 255, 255));
        deleteButtonPanel.setText("Delete");
        deleteButtonPanel.setName("displayButtonPanel"); // NOI18N
        deleteButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteButtonPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deleteButtonPanelMouseReleased(evt);
            }
        });
        deletePanel.add(deleteButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 70, 66));

        dropPanel.setBackground(new java.awt.Color(85, 85, 116));
        dropPanel.setName("displayPanel"); // NOI18N
        dropPanel.setPreferredSize(new java.awt.Dimension(250, 90));
        dropPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dropPanelMousePressed(evt);
            }
        });
        dropPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dropButtonPanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dropButtonPanel.setForeground(new java.awt.Color(255, 255, 255));
        dropButtonPanel.setText("Drop");
        dropButtonPanel.setName("displayButtonPanel"); // NOI18N
        dropButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dropButtonPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dropButtonPanelMouseReleased(evt);
            }
        });
        dropPanel.add(dropButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 80, 60));

        displayPanel.setBackground(new java.awt.Color(85, 85, 116));
        displayPanel.setMinimumSize(new java.awt.Dimension(250, 90));
        displayPanel.setName("displayPanel"); // NOI18N
        displayPanel.setPreferredSize(new java.awt.Dimension(250, 90));
        displayPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                displayPanelMousePressed(evt);
            }
        });
        displayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayButtonPanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        displayButtonPanel.setForeground(new java.awt.Color(255, 255, 255));
        displayButtonPanel.setText("  Display Table");
        displayButtonPanel.setName("displayButtonPanel"); // NOI18N
        displayPanel.add(displayButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 125, 66));

        searchPanel.setBackground(new java.awt.Color(85, 85, 116));
        searchPanel.setMinimumSize(new java.awt.Dimension(250, 90));
        searchPanel.setName("displayPanel"); // NOI18N
        searchPanel.setPreferredSize(new java.awt.Dimension(250, 90));
        searchPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchPanelMousePressed(evt);
            }
        });
        searchPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchButtonPanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchButtonPanel.setForeground(new java.awt.Color(255, 255, 255));
        searchButtonPanel.setText("Search");
        searchButtonPanel.setName("displayButtonPanel"); // NOI18N
        searchButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchButtonPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                searchButtonPanelMouseReleased(evt);
            }
        });
        searchPanel.add(searchButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 125, 66));

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dropPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(deletePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(enrollmentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(enrollmentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(dropPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(deletePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 1020));

        upperPanel.setBackground(new java.awt.Color(122, 72, 222));
        upperPanel.setName("upperPanel"); // NOI18N

        studentBIDLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        studentBIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentBIDLabel.setText(" Student B ID");

        studentBIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentBIdTextFieldActionPerformed(evt);
            }
        });

        dropStudentButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        dropStudentButton.setText("Drop Student");
        dropStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropStudentButtonActionPerformed(evt);
            }
        });

        ClassIDLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        ClassIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        ClassIDLabel.setText("    Class ID");

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(studentBIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studentBIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(upperPanelLayout.createSequentialGroup()
                        .addComponent(dropStudentButton)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperPanelLayout.createSequentialGroup()
                        .addComponent(ClassIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(classIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentBIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClassIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentBIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dropStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(upperPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 22, 950, -1));

        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(displayTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 950, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayPanelMousePressed
        // TODO add your handling code here:
        System.out.println("Button Display Clicked");
        dispose();
        DesignPage dp = new DesignPage();
        dp.setVisible(true);
    }//GEN-LAST:event_displayPanelMousePressed

    private void enrollmentPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrollmentPanelMousePressed
        // TODO add your handling code here:
        System.out.println("Button Clicked Enrollment");
        dispose();
        EnrollmentPage ep = new EnrollmentPage();
        ep.setVisible(true);
    }//GEN-LAST:event_enrollmentPanelMousePressed

    private void enrollmentButtonPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrollmentButtonPanelMousePressed
        // TODO add your handling code here:
        // Do Not Use this Method
    }//GEN-LAST:event_enrollmentButtonPanelMousePressed

    private void enrollmentButtonPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrollmentButtonPanelMouseReleased
        // TODO add your handling code here:
        // Do Not Use this Method
    }//GEN-LAST:event_enrollmentButtonPanelMouseReleased

    private void dropButtonPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropButtonPanelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropButtonPanelMousePressed

    private void dropButtonPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropButtonPanelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dropButtonPanelMouseReleased

    private void dropPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropPanelMousePressed
        // TODO add your handling code here:
        
        //Code Starts Here
    }//GEN-LAST:event_dropPanelMousePressed

    private void deleteButtonPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonPanelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonPanelMousePressed

    private void deleteButtonPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonPanelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonPanelMouseReleased

    private void deletePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletePanelMousePressed
        // TODO add your handling code here:
        dispose();
        DeletePage dp = new DeletePage();
        dp.setVisible(true);
    }//GEN-LAST:event_deletePanelMousePressed

    private void searchButtonPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonPanelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonPanelMousePressed

    private void searchButtonPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonPanelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonPanelMouseReleased

    private void searchPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchPanelMousePressed
        // TODO add your handling code here:
        dispose();
        SearchPage dp = new SearchPage();
        dp.setVisible(true);
    }//GEN-LAST:event_searchPanelMousePressed

    private void studentBIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentBIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentBIdTextFieldActionPerformed

    private void dropStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropStudentButtonActionPerformed
        // TODO add your handling code here:
        /*
        Input to this will be : Student B# and Class ID
        Procedure will have 3 Parameter : Student B# and Class ID OUT parameter will be VARCHAR to display the messages.
        */
        String studentBNum = studentBIdTextField.getText();
        String classID = classIdTextField.getText();

        OracleDataSource ds;
        Connection conn = null;
        try {
            //DB Connection
            ds = new oracle.jdbc.pool.OracleDataSource();
            ds.setURL("jdbc:oracle:thin:@castor.cc.binghamton.edu:1521:acad111");
            conn = ds.getConnection("hmense1", "HIMItejas06");
            System.out.println("Connection Successful");

            //Callable Statements for Stored Procedure
            CallableStatement cs = conn.prepareCall("{call course_registration.drop_student(?, ?, ?)}");
            cs.setString(1, studentBNum);
            cs.setString(2, classID);
            cs.registerOutParameter(3, OracleTypes.VARCHAR);
            cs.executeUpdate();
            String rset;
            rset = cs.getString(3);
            JOptionPane.showMessageDialog(null,
                rset,
                "Message",
                JOptionPane.INFORMATION_MESSAGE);
            
            //Commiting Transcation
                CallableStatement commitQuery=conn.prepareCall("commit");
		commitQuery.executeQuery();
		commitQuery.close();

        } catch (SQLException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null,
                "Oops, Some Error occured as could not esatblish a connection!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(SearchPage.class.getName()).log(Level.SEVERE, null, ex);
        }catch (Exception ex) {
            System.out.println(ex);
        }finally{
            try {
                conn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,
                    "Oops, Some Error occured as could not close a esatblished a connection properly!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                //Logger.getLogger(SearchPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_dropStudentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesignPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesignPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesignPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesignPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesignPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClassIDLabel;
    private javax.swing.JTextField classIdTextField;
    private javax.swing.JLabel deleteButtonPanel;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JLabel displayButtonPanel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JTable displayTable;
    private javax.swing.JLabel dropButtonPanel;
    private javax.swing.JPanel dropPanel;
    private javax.swing.JButton dropStudentButton;
    private javax.swing.JLabel enrollmentButtonPanel;
    private javax.swing.JPanel enrollmentPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel searchButtonPanel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel studentBIDLabel;
    private javax.swing.JTextField studentBIdTextField;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables
}
