
import java.sql.*;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import oracle.jdbc.OracleTypes;
import oracle.jdbc.pool.OracleDataSource;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hitea
 */
public class SearchPage extends javax.swing.JFrame {

    /**
     * Creates new form DesignPage
     */
    public SearchPage() {
        initComponents();
        showTAButton.setEnabled(false);
        showPreReqButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        enrollmentPanel = new javax.swing.JPanel();
        enrollmentButtonPanel = new javax.swing.JLabel();
        deletePanel = new javax.swing.JPanel();
        deleteButtonPanel = new javax.swing.JLabel();
        dropPanel = new javax.swing.JPanel();
        dropButtonPanel = new javax.swing.JLabel();
        displayPanel = new javax.swing.JPanel();
        displayButtonPanel = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        searchButtonPanel = new javax.swing.JLabel();
        searchTableComboBox = new javax.swing.JComboBox<>();
        upperPanel = new javax.swing.JPanel();
        showTATextField = new javax.swing.JTextField();
        showTALabel = new javax.swing.JLabel();
        showPreReqButton = new javax.swing.JButton();
        showPreReqDeptCodeLabel = new javax.swing.JLabel();
        courseNumTextField = new javax.swing.JTextField();
        showPreReqCourseNoLabel = new javax.swing.JLabel();
        deptCodeTextField = new javax.swing.JTextField();
        showTAButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setName("mainFrame"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(54, 33, 89));
        sidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        sidePanel.setName("sidePanel"); // NOI18N

        enrollmentPanel.setBackground(new java.awt.Color(85, 85, 116));
        enrollmentPanel.setName("displayPanel"); // NOI18N
        enrollmentPanel.setPreferredSize(new java.awt.Dimension(250, 90));
        enrollmentPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enrollmentPanelMousePressed(evt);
            }
        });
        enrollmentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enrollmentButtonPanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        enrollmentButtonPanel.setForeground(new java.awt.Color(255, 255, 255));
        enrollmentButtonPanel.setText("Enrollment");
        enrollmentButtonPanel.setName("displayButtonPanel"); // NOI18N
        enrollmentButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enrollmentButtonPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                enrollmentButtonPanelMouseReleased(evt);
            }
        });
        enrollmentPanel.add(enrollmentButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 125, 60));

        deletePanel.setBackground(new java.awt.Color(85, 85, 116));
        deletePanel.setName("displayPanel"); // NOI18N
        deletePanel.setPreferredSize(new java.awt.Dimension(250, 90));
        deletePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deletePanelMousePressed(evt);
            }
        });
        deletePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteButtonPanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deleteButtonPanel.setForeground(new java.awt.Color(255, 255, 255));
        deleteButtonPanel.setText("Delete");
        deleteButtonPanel.setName("displayButtonPanel"); // NOI18N
        deleteButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteButtonPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deleteButtonPanelMouseReleased(evt);
            }
        });
        deletePanel.add(deleteButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 60, 66));

        dropPanel.setBackground(new java.awt.Color(85, 85, 116));
        dropPanel.setName("displayPanel"); // NOI18N
        dropPanel.setPreferredSize(new java.awt.Dimension(250, 90));
        dropPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dropPanelMousePressed(evt);
            }
        });
        dropPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dropButtonPanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dropButtonPanel.setForeground(new java.awt.Color(255, 255, 255));
        dropButtonPanel.setText("Drop");
        dropButtonPanel.setName("displayButtonPanel"); // NOI18N
        dropButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dropButtonPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dropButtonPanelMouseReleased(evt);
            }
        });
        dropPanel.add(dropButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 50, 60));

        displayPanel.setBackground(new java.awt.Color(85, 85, 116));
        displayPanel.setMinimumSize(new java.awt.Dimension(250, 90));
        displayPanel.setName("displayPanel"); // NOI18N
        displayPanel.setPreferredSize(new java.awt.Dimension(250, 90));
        displayPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                displayPanelMousePressed(evt);
            }
        });
        displayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayButtonPanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        displayButtonPanel.setForeground(new java.awt.Color(255, 255, 255));
        displayButtonPanel.setText("  Display Table");
        displayButtonPanel.setName("displayButtonPanel"); // NOI18N
        displayPanel.add(displayButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 140, 30));

        searchPanel.setBackground(new java.awt.Color(85, 85, 116));
        searchPanel.setMinimumSize(new java.awt.Dimension(250, 90));
        searchPanel.setName("displayPanel"); // NOI18N
        searchPanel.setPreferredSize(new java.awt.Dimension(250, 90));
        searchPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchPanelMousePressed(evt);
            }
        });
        searchPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchButtonPanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchButtonPanel.setForeground(new java.awt.Color(255, 255, 255));
        searchButtonPanel.setText("Search");
        searchButtonPanel.setName("displayButtonPanel"); // NOI18N
        searchButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchButtonPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                searchButtonPanelMouseReleased(evt);
            }
        });
        searchPanel.add(searchButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, 66));

        searchTableComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TAs", "Prerequisites" }));
        searchTableComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTableComboBoxActionPerformed(evt);
            }
        });
        searchPanel.add(searchTableComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 140, 30));

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dropPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(deletePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(enrollmentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(enrollmentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(dropPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(deletePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 1020));

        upperPanel.setBackground(new java.awt.Color(122, 72, 222));
        upperPanel.setName("upperPanel"); // NOI18N

        showTALabel.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        showTALabel.setForeground(new java.awt.Color(255, 255, 255));
        showTALabel.setText("Class ID :");

        showPreReqButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        showPreReqButton.setText("Show Pre Req");
        showPreReqButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPreReqButtonActionPerformed(evt);
            }
        });

        showPreReqDeptCodeLabel.setBackground(new java.awt.Color(255, 255, 255));
        showPreReqDeptCodeLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        showPreReqDeptCodeLabel.setForeground(new java.awt.Color(255, 255, 255));
        showPreReqDeptCodeLabel.setText("Deptartment Code");

        courseNumTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        courseNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseNumTextFieldActionPerformed(evt);
            }
        });

        showPreReqCourseNoLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        showPreReqCourseNoLabel.setForeground(new java.awt.Color(255, 255, 255));
        showPreReqCourseNoLabel.setText("Course #");

        showTAButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        showTAButton.setText("Show TA");
        showTAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTAButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(showTALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(showTATextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(showPreReqDeptCodeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deptCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(showPreReqCourseNoLabel)
                .addGap(18, 18, 18)
                .addComponent(courseNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(showTAButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(showPreReqButton)
                .addGap(233, 233, 233))
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showTALabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(showTATextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(showPreReqDeptCodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(courseNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(showPreReqCourseNoLabel)
                        .addComponent(deptCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showTAButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showPreReqButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(upperPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 22, 930, 100));

        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(displayTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 125, 930, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayPanelMousePressed
        // TODO add your handling code here:
        //System.out.println("Button Display Clicked");
        dispose();
        DesignPage dp = new DesignPage();
        dp.setVisible(true);
    }//GEN-LAST:event_displayPanelMousePressed

    private void enrollmentPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrollmentPanelMousePressed
        // TODO add your handling code here:
        System.out.println("Button Clicked Enrollment");
        dispose();
        EnrollmentPage ep = new EnrollmentPage();
        ep.setVisible(true);
    }//GEN-LAST:event_enrollmentPanelMousePressed

    private void enrollmentButtonPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrollmentButtonPanelMousePressed
        // TODO add your handling code here:
        // Do Not Use this Method
    }//GEN-LAST:event_enrollmentButtonPanelMousePressed

    private void enrollmentButtonPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrollmentButtonPanelMouseReleased
        // TODO add your handling code here:
        // Do Not Use this Method
    }//GEN-LAST:event_enrollmentButtonPanelMouseReleased

    private void dropButtonPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropButtonPanelMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dropButtonPanelMousePressed

    private void dropButtonPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropButtonPanelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dropButtonPanelMouseReleased

    private void dropPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropPanelMousePressed
        // TODO add your handling code here:
        dispose();
        DropPage dp = new DropPage();
        dp.setVisible(true);
    }//GEN-LAST:event_dropPanelMousePressed

    private void deleteButtonPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonPanelMousePressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_deleteButtonPanelMousePressed

    private void deleteButtonPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonPanelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonPanelMouseReleased

    private void deletePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletePanelMousePressed
        // TODO add your handling code here:
        dispose();
        DeletePage dp = new DeletePage();
        dp.setVisible(true);
    }//GEN-LAST:event_deletePanelMousePressed

    private void searchButtonPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonPanelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonPanelMousePressed

    private void searchButtonPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonPanelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonPanelMouseReleased

    private void searchPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchPanelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchPanelMousePressed

    private void searchTableComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTableComboBoxActionPerformed
    if (searchTableComboBox.getSelectedItem()=="TAs"){
        DefaultTableModel model = (DefaultTableModel) displayTable.getModel();
        model.setRowCount(0);
         showTAButton.setEnabled(true);
         showPreReqButton.setEnabled(false);
    }  
    if (searchTableComboBox.getSelectedItem()=="Prerequisites"){
        DefaultTableModel model = (DefaultTableModel) displayTable.getModel();
        model.setRowCount(0);
        showTAButton.setEnabled(false);
         showPreReqButton.setEnabled(true);
    }  // TODO add your handling code here:
    }//GEN-LAST:event_searchTableComboBoxActionPerformed

    private void courseNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseNumTextFieldActionPerformed

    private void showPreReqButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPreReqButtonActionPerformed
        /* Pre Req Procedure Call
        Input Required : Dept Code and Course #
        Output : All Course with Dept Code and Course # 
        which are direct as well as indirect Pre Req for this course
       */
        
        String deptCode = deptCodeTextField.getText();
        String courseNum = courseNumTextField.getText();
        int courseNumInteger = Integer.parseInt(courseNum);
        
             OracleDataSource ds;
             Connection conn = null;
             ResultSet rset;    
             String rset1 =null;
            try {
                //DB Connection
                ds = new oracle.jdbc.pool.OracleDataSource();
                ds.setURL("jdbc:oracle:thin:@castor.cc.binghamton.edu:1521:acad111");
                conn = ds.getConnection("hmense1", "HIMItejas06");
                System.out.println("Connection Successful");
                
                //Callable Statements for Stored Procedure
                CallableStatement cs = conn.prepareCall("{call search_tuples.search_prerequisites_course(?, ?, ?, ?)}");
		cs.setString(1, deptCode);
		cs.setInt(2, courseNumInteger);
		cs.registerOutParameter(3, OracleTypes.CURSOR);
                cs.registerOutParameter(4, OracleTypes.VARCHAR);
                
		cs.executeUpdate();
		rset = (ResultSet) cs.getObject(3);
                rset1 = cs.getString(4);
                
                displayTable.setModel(DbUtils.resultSetToTableModel(rset));
                
        } catch (SQLException ex) {
                System.out.println(ex);
            JOptionPane.showMessageDialog(null,
                                "Oops, Some Error occured as could not esatblish a connection!",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(SearchPage.class.getName()).log(Level.SEVERE, null, ex);
        }catch (NullPointerException ex ) {
                System.out.println("Exception madhe gela");
            JOptionPane.showMessageDialog(null,
                                rset1,
                                "Error",
                                JOptionPane.ERROR_MESSAGE);    
            System.out.println(ex);
            //Logger.getLogger(SearchPage.class.getName()).log(Level.SEVERE, null, ex);
        } 
            catch (IllegalArgumentException ex ) {
                System.out.println("Exception madhe gela");
            JOptionPane.showMessageDialog(null,
                                rset1,
                                "Error",
                                JOptionPane.ERROR_MESSAGE);    
            System.out.println(ex);
            //Logger.getLogger(SearchPage.class.getName()).log(Level.SEVERE, null, ex);
        }
            catch (Exception ex) {
                System.out.println(ex);
            //Logger.getLogger(SearchPage.class.getName()).log(Level.SEVERE, null, ex);
        }
            finally{
            try {
                conn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,
                                "Oops, Some Error occured as could not close a esatblished a connection properly!",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                //Logger.getLogger(SearchPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
               
    }//GEN-LAST:event_showPreReqButtonActionPerformed

    private void showTAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTAButtonActionPerformed
        // TODO add your handling code here:
        // Show TA action is performed over here
        /*
        Input to this will be : Class ID
        If Class ID found and has TA then show it in table
        If Class ID found but No Rows Fetched then display JoptionPane as No TA for this class
        If Class ID is not in table then show message as Oops! No Class ID only
        
        Procedure will have 2 Parameters : One is ClassID and Other is either VARCHAR or Cursor
        */
        
        String classID = showTATextField.getText();
        
        
             OracleDataSource ds;
             Connection conn = null;
             String rset1=null;
            try {
                //DB Connection
                ds = new oracle.jdbc.pool.OracleDataSource();
                ds.setURL("jdbc:oracle:thin:@castor.cc.binghamton.edu:1521:acad111");
                conn = ds.getConnection("hmense1", "HIMItejas06");
                System.out.println("Connection Successful");
                
                //Statement Creation
                Statement stmt = conn.createStatement();

		stmt = null;
               
                //Callable Statements for Stored Procedure Change this call 
                CallableStatement cs = conn.prepareCall("{call search_tuples.search_TA(?,?,?)}");
		cs.setString(1, classID);
                cs.registerOutParameter(2, OracleTypes.VARCHAR);
		cs.registerOutParameter(3, OracleTypes.CURSOR);
		cs.execute();
                ResultSet rset;      
		rset = (ResultSet) cs.getObject(3);
                rset1 = cs.getString(2);
                
                displayTable.setModel(DbUtils.resultSetToTableModel(rset));    
		
                
        } catch (SQLException ex) {
                System.out.println(ex);
            JOptionPane.showMessageDialog(null,
                                "Oops, Some Error occured as could not esatblish a connection!",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(SearchPage.class.getName()).log(Level.SEVERE, null, ex);
        }catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null,
                                rset1,
                                "Error",
                                JOptionPane.ERROR_MESSAGE);    
            System.out.println(ex);
            //Logger.getLogger(SearchPage.class.getName()).log(Level.SEVERE, null, ex);
        }catch (IllegalArgumentException ex ) {
                System.out.println("Exception madhe gela");
            JOptionPane.showMessageDialog(null,
                                rset1,
                                "Error",
                                JOptionPane.ERROR_MESSAGE);    
            System.out.println(ex);
            //Logger.getLogger(SearchPage.class.getName()).log(Level.SEVERE, null, ex);
        }catch (Exception ex) {
//            JOptionPane.showMessageDialog(null,
//                                "Oops, Class has No TA!",
//                                "Error",
//                                JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(SearchPage.class.getName()).log(Level.SEVERE, null, ex);
        }
            finally{
            try {
                conn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,
                                "Oops, Some Error occured as could not close a esatblished a connection properly!",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                //Logger.getLogger(SearchPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
    }//GEN-LAST:event_showTAButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesignPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesignPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesignPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesignPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField courseNumTextField;
    private javax.swing.JLabel deleteButtonPanel;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JTextField deptCodeTextField;
    private javax.swing.JLabel displayButtonPanel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JTable displayTable;
    private javax.swing.JLabel dropButtonPanel;
    private javax.swing.JPanel dropPanel;
    private javax.swing.JLabel enrollmentButtonPanel;
    private javax.swing.JPanel enrollmentPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel searchButtonPanel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JComboBox<String> searchTableComboBox;
    private javax.swing.JButton showPreReqButton;
    private javax.swing.JLabel showPreReqCourseNoLabel;
    private javax.swing.JLabel showPreReqDeptCodeLabel;
    private javax.swing.JButton showTAButton;
    private javax.swing.JLabel showTALabel;
    private javax.swing.JTextField showTATextField;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables
}
